/*
 * ADC_config.h
 *
 * Created: 2/14/2024 2:33:45 AM
 *  Author: ahmed
 */ 


#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_

#define ADC_U32TIME_OUT				50000
#define ADC_INITIAL_STATE			ADC_ENABLE
#define ADC_REFRENCE_SELECTION		ADC_AVCC
#define ADC_PRESCALER_SELECTION		PRESCALER_128
#define ADC_RESOLUTION				ADC_10BIT_RESOLUTION
#define	ADC_ADJUSTMENT				ADC_LEFT_ADJUST
#define ADC_AUTO_TRIGGER_STATE		ADC_AUTO_TRIGGER_ENABLE
#define ADC_AUTO_TRIGGER_SOURCE		ADC_FREE_RUNNING_MODE






#endif /* ADC_CONFIG_H_ */